services:
  - type: web
    name: coony-django
    env: python
    plan: free
    region: oregon
    repo: https://github.com/joelysom/Coony-Django-Transforme-se
    branch: vercel
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn coony.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --log-file -
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: coony.settings
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: DJANGO_DEBUG
        value: "False"
